import { FormEvent, useEffect, useState } from "react";
import { AdminUser, api, Booking, Closure, Equipment, Room, Session } from "./api";

const futureDate = () => { const date = new Date(); date.setDate(date.getDate() + 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
type AdminBooking = Booking & { user: { name: string; email: string } };

export function AdminOperations({ session }: { session: Session }) {
  const [users, setUsers] = useState<AdminUser[]>([]); const [rooms, setRooms] = useState<Room[]>([]); const [equipment, setEquipment] = useState<Equipment[]>([]); const [bookings, setBookings] = useState<AdminBooking[]>([]); const [closures, setClosures] = useState<Closure[]>([]); const [roomId, setRoomId] = useState(""); const [selectedEquipment, setSelectedEquipment] = useState<string[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { try { const [nextUsers, nextRooms, nextEquipment, nextBookings] = await Promise.all([api.adminUsers(session.token), api.adminRooms(session.token), api.equipment(session.token), api.adminBookings(session.token)]); setUsers(nextUsers); setRooms(nextRooms); setEquipment(nextEquipment); setBookings(nextBookings); setRoomId((current) => current || nextRooms[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không tải được dữ liệu quản trị."); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { const room = rooms.find((item) => item.id === roomId); setSelectedEquipment(room?.equipment.map((item) => item.equipment.id) || []); if (roomId) api.closures(session.token, roomId).then(setClosures).catch(() => setClosures([])); }, [roomId, rooms]);
  const action = async (work: () => Promise<unknown>, message: string) => { setError(""); try { await work(); setNotice(message); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Thao tác không thành công."); } };
  const submitEquipment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const target = event.currentTarget; const form = new FormData(target); void action(async () => { await api.createEquipment(session.token, String(form.get("equipment"))); target.reset(); }, "Đã thêm thiết bị."); };
  const submitClosure = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const target = event.currentTarget; const form = new FormData(target); void action(async () => { await api.createClosure(session.token, roomId, String(form.get("date")), String(form.get("reason"))); target.reset(); }, "Đã đóng phòng theo lịch."); };
  const submitRoomUpdate = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action(() => api.updateRoom(session.token, roomId, { capacity: Number(form.get("capacity")), location: String(form.get("location")) }), "Đã cập nhật thông tin phòng."); };
  const saveEquipment = () => void action(() => api.setRoomEquipment(session.token, roomId, selectedEquipment), "Đã cập nhật thiết bị cho phòng.");
  return <section className="mt-6 grid gap-6 xl:grid-cols-2">
    {notice && <p role="status" className="rounded-xl bg-emerald-50 px-3 py-2 text-sm text-emerald-700 xl:col-span-2">{notice}</p>}{error && <p role="alert" className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700 xl:col-span-2">{error}</p>}
    <article className="card p-5"><h2 className="text-xl font-bold">Phòng & lịch đóng</h2><p className="mt-1 text-sm text-slate-500">Chuyển trạng thái để bảo toàn lịch sử booking thay vì xóa phòng.</p><div className="mt-4 space-y-2">{rooms.map((room) => <div className="flex items-center justify-between gap-2 rounded-xl bg-slate-50 p-3" key={room.id}><div><b>{room.name}</b><p className="text-xs text-slate-500">{room.capacity} chỗ · {room.location}</p></div><button className="button-secondary text-xs" onClick={() => void action(() => api.setRoomStatus(session.token, room.id, room.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"), "Đã cập nhật trạng thái phòng.")}>{room.status === "ACTIVE" ? "Ngừng hoạt động" : "Kích hoạt"}</button></div>)}</div><label className="mt-4 block"><span className="label">Phòng cần cấu hình</span><select className="field" aria-label="Phòng cấu hình" value={roomId} onChange={(event) => setRoomId(event.target.value)}>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label><div className="mt-3 grid gap-2 sm:grid-cols-2">{equipment.map((item) => <label className="flex items-center gap-2 text-sm" key={item.id}><input type="checkbox" checked={selectedEquipment.includes(item.id)} onChange={(event) => setSelectedEquipment((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} />{item.name}</label>)}</div><button className="button-secondary mt-3" onClick={saveEquipment} disabled={!roomId}>Lưu thiết bị cho phòng</button><form className="mt-4 grid gap-2 sm:grid-cols-3" onSubmit={submitRoomUpdate}><input className="field" name="capacity" type="number" min="1" placeholder="Sức chứa mới" required/><input className="field" name="location" placeholder="Vị trí mới" required/><button className="button-secondary">Cập nhật phòng đã chọn</button></form><form className="mt-4 grid gap-2 sm:grid-cols-3" onSubmit={submitClosure}><input className="field" name="date" type="date" min={futureDate()} required/><input className="field" name="reason" minLength={3} placeholder="Lý do đóng" required/><button className="button-primary sm:col-span-3">Thêm lịch đóng</button></form><div className="mt-3 space-y-2">{closures.map((closure) => <div className="flex justify-between text-sm" key={closure.id}><span>{closure.date} · {closure.reason}</span><button className="text-rose-600" onClick={() => void action(() => api.deleteClosure(session.token, closure.id), "Đã xóa lịch đóng.")}>Xóa</button></div>)}</div></article>
    <article className="card p-5"><h2 className="text-xl font-bold">Thiết bị</h2><form className="mt-4 flex gap-2" onSubmit={submitEquipment}><input className="field" name="equipment" minLength={2} placeholder="Ví dụ: Máy chiếu" required/><button className="button-primary">Thêm</button></form><div className="mt-4 space-y-2">{equipment.map((item) => <div className="flex justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm" key={item.id}><span>{item.name} <small className="text-slate-500">({item._count?.rooms || 0} phòng)</small></span><button className="text-rose-600" onClick={() => void action(() => api.deleteEquipment(session.token, item.id), "Đã xóa thiết bị.")}>Xóa</button></div>)}</div></article>
    <article className="card p-5"><h2 className="text-xl font-bold">Người dùng & quyền</h2><div className="mt-4 space-y-2">{users.map((user) => <div className="flex items-center justify-between gap-2 rounded-xl bg-slate-50 px-3 py-2 text-sm" key={user.id}><span>{user.name}<small className="block text-slate-500">{user.email}</small></span><button className="button-secondary text-xs" disabled={user.id === session.user.id} onClick={() => void action(() => api.setUserRole(session.token, user.id, user.role === "ADMIN" ? "STUDENT" : "ADMIN"), "Đã cập nhật quyền người dùng.")}>{user.role === "ADMIN" ? "Chuyển Student" : "Chuyển Admin"}</button></div>)}</div></article>
    <article className="card p-5"><h2 className="text-xl font-bold">Booking gần đây</h2><div className="mt-4 max-h-72 space-y-2 overflow-auto">{bookings.length ? bookings.map((booking) => <div className="rounded-xl bg-slate-50 px-3 py-2 text-sm" key={booking.id}><b>{booking.room.name} · {booking.date} {booking.startTime}</b><p className="text-slate-500">{booking.user.name} · {booking.status}</p><select aria-label={`Trạng thái ${booking.id}`} className="field mt-2" value={booking.status} onChange={(event) => void action(() => api.setBookingStatus(session.token, booking.id, event.target.value as "BOOKED" | "CANCELLED" | "CHECKED_IN" | "NO_SHOW"), "Đã cập nhật trạng thái booking.")}>{["BOOKED", "CHECKED_IN", "NO_SHOW", "CANCELLED"].map((status) => <option key={status}>{status}</option>)}</select></div>) : <p className="text-sm text-slate-500">Chưa có booking.</p>}</div></article>
  </section>;
}
