import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, Session } from "./api";
import { AdminOperations } from "./AdminOperations";
import { StudentProfile } from "./StudentProfile";
import { BookingPanel as BookingPanelV2 } from "./BookingPanel";

const storedSession = (): Session | null => { try { return JSON.parse(localStorage.getItem("studyspace.session") || "null"); } catch { return null; } };

function Notice({ message, type = "error" }: { message: string; type?: "error" | "success" }) {
  return <p role="alert" className={`rounded-xl px-3 py-2 text-sm ${type === "success" ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{message}</p>;
}

function Auth({ onSession }: { onSession: (session: Session) => void }) {
  const [mode, setMode] = useState<"login" | "register">("login"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget);
    try { const session = mode === "login" ? await api.login(String(data.get("email")), String(data.get("password"))) : await api.register(String(data.get("name")), String(data.get("email")), String(data.get("password"))); onSession(session); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể xác thực."); } finally { setLoading(false); }
  }
  return <main className="mx-auto grid min-h-screen max-w-6xl items-center gap-10 px-6 py-12 lg:grid-cols-2">
    <section><span className="rounded-full bg-brand/10 px-3 py-1 text-sm font-bold text-brand">StudySpace</span><h1 className="mt-5 text-4xl font-black leading-tight md:text-6xl">Đặt đúng chỗ.<br/><span className="text-brand">Học đúng nhịp.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Không gian học tập minh bạch, lịch đặt rõ ràng và vận hành dựa trên dữ liệu.</p><div className="mt-8 grid grid-cols-3 gap-3 text-center"><div className="card p-4"><b className="text-xl">14</b><p className="text-xs text-slate-500">slot mỗi ngày</p></div><div className="card p-4"><b className="text-xl">1h</b><p className="text-xs text-slate-500">mỗi lượt học</p></div><div className="card p-4"><b className="text-xl">24/7</b><p className="text-xs text-slate-500">xem lịch</p></div></div></section>
    <section className="card p-6 md:p-8"><h2 className="text-2xl font-bold">{mode === "login" ? "Chào mừng trở lại" : "Tạo tài khoản"}</h2><p className="mt-1 text-sm text-slate-500">{mode === "login" ? "Đăng nhập để quản lý lịch học của bạn." : "Bắt đầu tìm không gian phù hợp."}</p>
      <form className="mt-6 space-y-4" onSubmit={submit}>{mode === "register" && <label><span className="label">Họ và tên</span><input required name="name" className="field" placeholder="Nguyễn Minh Anh"/></label>}<label><span className="label">Email</span><input required type="email" name="email" className="field" placeholder="ban@phenikaa-uni.edu.vn"/></label><label><span className="label">Mật khẩu</span><input required minLength={8} type="password" name="password" className="field" placeholder="Tối thiểu 8 ký tự"/></label>{error && <Notice message={error}/>}<button disabled={loading} className="button-primary w-full">{loading ? "Đang xử lý..." : mode === "login" ? "Đăng nhập" : "Tạo tài khoản"}</button></form>
      <button className="mt-5 text-sm font-semibold text-brand" onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }}>{mode === "login" ? "Chưa có tài khoản? Đăng ký" : "Đã có tài khoản? Đăng nhập"}</button><p className="mt-6 rounded-xl bg-slate-50 p-3 text-xs text-slate-500">Tài khoản demo sau khi seed: admin@studyspace.local hoặc student@studyspace.local — mật khẩu StudySpace123!</p>
    </section>
  </main>;
}

function AdminPanel({ session }: { session: Session }) {
  const [report, setReport] = useState<{ totals: { bookings: number; checkedIn: number; noShow: number; reservationRate: number; utilizationRate: number }; rooms: { roomName: string; bookings: number }[] } | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = () => api.usage(session.token).then(setReport).catch((reason) => setError(reason instanceof Error ? reason.message : "Không tải được báo cáo."));
  useEffect(() => { void load(); }, []);
  async function createRoom(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api.adminRoom(session.token, { name: String(data.get("name")), capacity: Number(data.get("capacity")), location: String(data.get("location")), equipment: String(data.get("equipment")).split(",").map((item) => item.trim()).filter(Boolean) }); setMessage("Đã tạo phòng mới và lưu audit log."); event.currentTarget.reset(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tạo phòng."); } }
  return <><div className="grid gap-6 lg:grid-cols-2"><section className="card p-5"><h2 className="text-xl font-bold">Tổng quan vận hành</h2>{error && <div className="mt-4"><Notice message={error}/></div>}{report ? <><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="Tổng booking" value={report.totals.bookings}/><Metric label="Đã check-in" value={report.totals.checkedIn}/><Metric label="Tỷ lệ đặt chỗ" value={`${report.totals.reservationRate}%`}/><Metric label="Tỷ lệ sử dụng thực tế" value={`${report.totals.utilizationRate}%`}/></div><p className="mt-2 text-xs text-slate-500">No-show: {report.totals.noShow} lượt.</p><h3 className="mt-6 font-bold">Phòng được đặt nhiều</h3><div className="mt-3 space-y-2">{report.rooms.length ? report.rooms.map((room) => <div className="flex justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm" key={room.roomName}><span>{room.roomName}</span><b>{room.bookings} lượt</b></div>) : <p className="text-sm text-slate-500">Chưa có dữ liệu booking.</p>}</div></> : <p className="mt-5 text-slate-500">Đang tổng hợp báo cáo...</p>}</section><section className="card p-5"><h2 className="text-xl font-bold">Thêm phòng mới</h2><p className="mt-1 text-sm text-slate-500">Thay đổi này sẽ được lưu vết trong audit log.</p>{message && <div className="mt-4"><Notice type="success" message={message}/></div>}<form className="mt-5 space-y-3" onSubmit={createRoom}><label><span className="label">Tên phòng</span><input required className="field" name="name" placeholder="D405"/></label><label><span className="label">Sức chứa</span><input required className="field" name="capacity" type="number" min="1" max="500" placeholder="16"/></label><label><span className="label">Vị trí</span><input required className="field" name="location" placeholder="Tòa D – Tầng 4"/></label><label><span className="label">Thiết bị</span><input className="field" name="equipment" placeholder="Máy chiếu, Bảng trắng"/></label><button className="button-primary w-full">Tạo phòng</button></form></section></div><AdminOperations session={session}/></>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl bg-brand/5 p-4"><p className="text-xs font-medium text-slate-600">{label}</p><b className="mt-1 block text-2xl text-brand">{value}</b></div>; }

export default function App() {
  const [session, setSession] = useState<Session | null>(storedSession); const [tab, setTab] = useState<"student" | "admin">("student");
  const saveSession = (next: Session) => { localStorage.setItem("studyspace.session", JSON.stringify(next)); setSession(next); setTab(next.user.role === "ADMIN" ? "admin" : "student"); };
  const greeting = useMemo(() => session?.user.name.split(" ").at(-1), [session]);
  if (!session) return <Auth onSession={saveSession}/>;
  const isAdmin = session.user.role === "ADMIN";
  const updateProfile = (user: Session["user"]) => { const next = { ...session, user }; localStorage.setItem("studyspace.session", JSON.stringify(next)); setSession(next); };
  return <><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><button className="text-xl font-black tracking-tight" onClick={() => setTab(isAdmin ? "admin" : "student")}>Study<span className="text-brand">Space</span></button><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-500 sm:inline">Xin chào, {greeting}</span><button onClick={() => { localStorage.removeItem("studyspace.session"); setSession(null); }} className="button-secondary text-sm">Đăng xuất</button></div></div></header><main className="mx-auto max-w-7xl px-5 py-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-brand">{isAdmin && tab === "admin" ? "ADMIN CONSOLE" : "STUDENT PORTAL"}</p><h1 className="mt-1 text-3xl font-black">{isAdmin && tab === "admin" ? "Vận hành không gian học tập" : "Chọn không gian, giữ nhịp tập trung"}</h1></div>{isAdmin && <div className="rounded-xl bg-white p-1 shadow-sm"><button className={`button text-sm ${tab === "admin" ? "bg-ink text-white" : "text-slate-600"}`} onClick={() => setTab("admin")}>Quản trị</button><button className={`button text-sm ${tab === "student" ? "bg-ink text-white" : "text-slate-600"}`} onClick={() => setTab("student")}>Góc nhìn sinh viên</button></div>}</div>{isAdmin && tab === "admin" ? <AdminPanel session={session}/> : <><BookingPanelV2 session={session}/><StudentProfile session={session} onUpdate={updateProfile}/></>}</main></>;
}
